name: CI/CD Pipeline for HTML Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML files
        run: htmlhint "**/*.html"

  deploy:
    needs: lint-html
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # assuming your site files are in the root directory

